version: '3.8'

services:
  web:
    build:
      context: ..
      dockerfile: Dockerfile.prod
    command: gunicorn sirayastein.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/code/web/staticfiles
    expose:
      - 8000
    env_file:
      - ../.env.prod
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ../.env.prod.db
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]

  nginx:
    build: ../nginx
    volumes:
      - static_volume:/home/code/web/staticfiles
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume: