# Generated by Django 4.2.4 on 2023-08-05 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catEn', models.CharField(max_length=200, verbose_name='Categoría inglés')),
                ('catEs', models.CharField(blank=True, max_length=200, null=True, verbose_name='Categoría español')),
                ('urlEn', models.URLField(blank=True, max_length=2000, null=True, verbose_name='Enlace Coppermind en inglés')),
                ('urlEs', models.URLField(blank=True, max_length=2000, null=True, verbose_name='Enlace Coppermind en español')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Glossary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wordEn', models.CharField(max_length=200, verbose_name='Palabra inglés')),
                ('wordEs', models.CharField(blank=True, max_length=200, null=True, verbose_name='Palabra español')),
                ('urlEn', models.URLField(blank=True, max_length=2000, null=True, verbose_name='Enlace Coppermind en inglés')),
                ('urlEs', models.URLField(blank=True, max_length=2000, null=True, verbose_name='Enlace Coppermind en español')),
                ('universe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='glossary_universe', to='login_app.universe', verbose_name='Universo')),
            ],
            options={
                'verbose_name': 'Glosario',
                'verbose_name_plural': 'Glosario',
            },
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pageidEn', models.IntegerField(blank=True, null=True, verbose_name='ID Coppermind en inglés')),
                ('pageidEs', models.IntegerField(blank=True, null=True, verbose_name='ID Coppermind en español')),
                ('titleEn', models.CharField(blank=True, max_length=200, null=True, verbose_name='Título inglés')),
                ('titleEs', models.CharField(blank=True, max_length=200, null=True, verbose_name='Título español')),
                ('type', models.CharField(blank=True, choices=[('CU', 'Cultura'), ('EVT', 'Eventos y eras'), ('FDV', 'Formas de vida'), ('LIB', 'Libros'), ('LOC', 'Localizaciones'), ('MG', 'Magia'), ('PJ', 'Personajes'), ('OBJ', 'Objetos y materiales'), ('ORG', 'Organización'), ('FAM', 'Familia'), ('MUL', 'Multimedia'), ('WIKI', 'Wiki/otros'), ('DIS', 'Disambiguación'), ('RD', 'Redirección'), ('SUB', 'Subpágina')], max_length=4, null=True, verbose_name='Tipo de artículo')),
                ('priority', models.CharField(blank=True, choices=[('1', 'Alta'), ('2', 'Media'), ('3', 'Baja'), ('4', 'TBD'), ('5', 'Siraya')], max_length=1, null=True, verbose_name='Prioridad')),
                ('assignedDate', models.DateField(blank=True, null=True, verbose_name='Fecha asignado traductor')),
                ('translated', models.BooleanField(default=False, verbose_name='Traducido')),
                ('translatedDate', models.DateField(blank=True, null=True, verbose_name='Fecha traducido')),
                ('reviewed', models.BooleanField(default=False, verbose_name='Revisado')),
                ('reviewerassignedDate', models.DateField(blank=True, null=True, verbose_name='Fecha asignado revisor')),
                ('reviewedDate', models.DateField(blank=True, null=True, verbose_name='Fecha revisado')),
                ('engregoriado', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notas')),
                ('urldrive', models.URLField(blank=True, null=True)),
                ('urlEn', models.URLField(blank=True, null=True, verbose_name='Enlace Coppermind en inglés')),
                ('urlEs', models.URLField(blank=True, null=True, verbose_name='Enlace Coppermind en español')),
                ('linkcopperen', models.BooleanField(default=False, verbose_name='Enlazada con la Coppermind en inglés')),
                ('problemCopper', models.TextField(blank=True, null=True, verbose_name='Problemas de la Copper')),
                ('gregorio', models.ForeignKey(blank=True, limit_choices_to={'is_superuser': True}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='gregorio', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Revisores'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reviewer', to=settings.AUTH_USER_MODEL, verbose_name='Revisor')),
                ('translator', models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Traductores'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='translator', to=settings.AUTH_USER_MODEL, verbose_name='Traductor')),
                ('universe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='article_universe', to='login_app.universe', verbose_name='Universo')),
            ],
            options={
                'verbose_name': 'Artículo',
                'verbose_name_plural': 'Artículos',
            },
        ),
    ]
